from commands.exceptions import CommandError


class StopEvent(CommandError):
    pass
